// ============================================================================
// Brand free-shipping specials — the pure half.
//
// A marketing special: "free shipping on all Robot Coupe this month". Staff set
// them up per storefront in the portal (Settings → Shipping), stored as the
// channel setting `free_shipping_brands`. An order containing ANY item from a
// promoted brand ships free — every customer, no minimum spend, only between the
// special's start and end dates (card 88Ay7UGA, decision 2026-08-11).
//
// WHY WHOLE-ORDER. Storefront delivery is a zone-based FLAT RATE PER ORDER
// (shipping_rate_cards), not per item, so "free freight on the branded items
// only" is not expressible: delivery is either the flat rate or $0. Exposure is
// therefore bounded at the zone rate, and it is a deliberate staff-enabled
// giveaway.
//
// This module is pure so the cart page, the checkout page and `placeOrder` all
// reach the same verdict from the same rows — the storefront's standing
// show-equals-accept rule.
// ============================================================================

/** One special, exactly as stored in `channel_settings.free_shipping_brands`. */
export type BrandFreeShippingSpecial = {
  /** Stable row id, generated by the portal (used as the React key / edit target). */
  id: string;
  brand_id: number;
  /** Inclusive, `YYYY-MM-DD` in Melbourne time. Empty/absent = no start bound. */
  start_date: string | null;
  /** Inclusive, `YYYY-MM-DD` in Melbourne time. Empty/absent = no end bound. */
  end_date: string | null;
  /** Manual kill switch, independent of the dates. Absent = enabled. */
  enabled: boolean;
};

/** A special matched against a cart, carrying the brand name for the message. */
export type MatchedBrandSpecial = {
  brandId: number;
  brandName: string | null;
  endDate: string | null;
};

const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;

/**
 * Today's date in Melbourne as `YYYY-MM-DD`.
 *
 * The dates a staff member types are Australian calendar dates, and the servers
 * run in UTC: comparing against a UTC date would start a special up to 11 hours
 * early and end it a day late for evening shoppers.
 */
export function todayInMelbourne(now: Date = new Date()): string {
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: "Australia/Melbourne",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(now);
}

/**
 * Read the stored setting into typed rows, dropping anything unusable.
 *
 * The value is operator-entered JSON, so a row without a real brand id is
 * discarded rather than defaulted — a special that matched brand 0 would give
 * away freight on carts it was never meant to touch.
 */
export function parseBrandFreeShippingSpecials(value: unknown): BrandFreeShippingSpecial[] {
  if (!Array.isArray(value)) return [];
  const out: BrandFreeShippingSpecial[] = [];
  for (const raw of value) {
    if (!raw || typeof raw !== "object") continue;
    const row = raw as Record<string, unknown>;
    const brandId = Number(row.brand_id);
    if (!Number.isInteger(brandId) || brandId <= 0) continue;
    out.push({
      id: typeof row.id === "string" && row.id ? row.id : `brand-${brandId}`,
      brand_id: brandId,
      start_date: typeof row.start_date === "string" && row.start_date ? row.start_date : null,
      end_date: typeof row.end_date === "string" && row.end_date ? row.end_date : null,
      enabled: row.enabled !== false,
    });
  }
  return out;
}

/**
 * Is this special running today?
 *
 * A date that is present but not `YYYY-MM-DD` makes the special INACTIVE. Free
 * shipping is money out the door, so an unreadable bound must never be read as
 * "no bound".
 */
export function isSpecialActive(special: BrandFreeShippingSpecial, today: string): boolean {
  if (!special.enabled) return false;
  if (special.start_date !== null) {
    if (!ISO_DATE.test(special.start_date)) return false;
    if (special.start_date > today) return false;
  }
  if (special.end_date !== null) {
    if (!ISO_DATE.test(special.end_date)) return false;
    if (special.end_date < today) return false;
  }
  return true;
}

/** Every special running today, in configured order. */
export function activeSpecials(
  specials: BrandFreeShippingSpecial[],
  today: string
): BrandFreeShippingSpecial[] {
  return specials.filter((s) => isSpecialActive(s, today));
}

/**
 * The first ACTIVE special whose brand appears in the cart, or null.
 *
 * `brandIds` is one entry per cart line (nulls tolerated — a product with no
 * brand simply never matches).
 */
export function matchBrandSpecial(
  activeOnes: MatchedBrandSpecial[],
  brandIds: Array<number | null | undefined>
): MatchedBrandSpecial | null {
  const inCart = new Set(brandIds.filter((b): b is number => typeof b === "number"));
  return activeOnes.find((s) => inCart.has(s.brandId)) ?? null;
}

/**
 * The customer-facing line for a matched special. Kept here so the cart summary
 * and the checkout summary cannot word it differently.
 */
export function brandFreeShippingMessage(match: MatchedBrandSpecial): string {
  return match.brandName
    ? `Free delivery on this order — ${match.brandName} free shipping special.`
    : "Free delivery on this order — free shipping special.";
}
